import type { MemoryDraft, MemoryRecord, MemoryStatus, Provenance } from './schema.js';

/** Categories that shape how an agent addresses the user, not merely what it knows. */
const IDENTITY_CATEGORIES = new Set(['identity', 'preference', 'relationship']);

/** Provenances that may never become durable identity without a human saying so. */
const UNTRUSTED_PROVENANCE = new Set<Provenance>(['external_content']);

export const DEFAULT_INFERENCE_THRESHOLD = 0.85;

export interface PolicyDecision {
  status: MemoryStatus;
  /** True when the record needs an explicit human decision before it takes effect. */
  requiresReview: boolean;
  reason: string;
}

export interface PolicyOptions {
  /** Confidence at or above which an agent-inferred memory is accepted without review. */
  inferenceThreshold?: number;
  /** Set only when a human has just confirmed this specific record. */
  userConfirmed?: boolean;
}

/**
 * Decide whether a candidate memory becomes active, waits for review, or is quarantined.
 *
 * The rules are deliberately conservative: a wrong memory is worse than a missing one,
 * because the user cannot see it and it silently steers every future agent.
 */
export function classify(
  draft: Pick<MemoryDraft, 'provenance' | 'category' | 'confidence' | 'sensitivity'>,
  options: PolicyOptions = {},
): PolicyDecision {
  const threshold = options.inferenceThreshold ?? DEFAULT_INFERENCE_THRESHOLD;

  if (options.userConfirmed) {
    return { status: 'active', requiresReview: false, reason: 'confirmed by the user' };
  }

  if (UNTRUSTED_PROVENANCE.has(draft.provenance)) {
    if (IDENTITY_CATEGORIES.has(draft.category)) {
      return {
        status: 'quarantined',
        requiresReview: true,
        reason: 'external content cannot become identity memory without explicit approval',
      };
    }
    return {
      status: 'pending_review',
      requiresReview: true,
      reason: 'external content is never trusted automatically',
    };
  }

  if (draft.sensitivity === 'secret') {
    return {
      status: 'quarantined',
      requiresReview: true,
      reason: 'looks like credential material and must not be stored as memory',
    };
  }

  switch (draft.provenance) {
    case 'user_explicit':
      return { status: 'active', requiresReview: false, reason: 'stated by the user' };
    case 'system_generated':
      return { status: 'active', requiresReview: false, reason: 'generated by Agent Passport' };
    case 'imported':
      // Imported memories come from config files the user authored themselves: CLAUDE.md,
      // AGENTS.md, and the like. That is the user speaking, one step removed, so gating it
      // behind review would mean a freshly restored agent knows nothing and the first run
      // delivers no value. The safety property that matters is that every memory is
      // visible and removable, not that each one is approved before it counts.
      return {
        status: 'active',
        requiresReview: false,
        reason: 'imported from your own agent config',
      };
    case 'agent_inferred':
      return (draft.confidence ?? 0) >= threshold
        ? { status: 'active', requiresReview: false, reason: 'high-confidence inference' }
        : {
            status: 'pending_review',
            requiresReview: true,
            reason: `inference below the ${threshold} confidence threshold`,
          };
    default:
      return { status: 'pending_review', requiresReview: true, reason: 'unknown provenance' };
  }
}

/** Whether a record may leave this device for a memory provider. */
export function isSyncable(record: MemoryRecord): boolean {
  if (!record.syncEnabled) return false;
  if (record.sensitivity === 'secret') return false;
  if (record.status === 'quarantined' || record.status === 'revoked') return false;
  return true;
}

/** Whether a record should be handed to an agent during `restore`. */
export function isRestorable(record: MemoryRecord): boolean {
  return record.status === 'active';
}

const SECRET_HINT =
  /\b(sk-[a-z0-9]{16,}|ghp_[a-z0-9]{20,}|xox[baprs]-[a-z0-9-]{10,}|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----|eyJ[\w-]{10,}\.[\w-]{10,}\.[\w-]{10,})/i;

/** Heuristic detector for credential material that must never be persisted as memory. */
export function looksLikeSecret(text: string): boolean {
  return SECRET_HINT.test(text);
}
